### PR TITLE
remove requiredness of alt text on images

### PR DESCRIPTION
**Pull request by TomWoodward**
http://redmine.oerpub.org/issues/192

### CODE REVIEW

**Comment by kathi-fletcher** [comment]
Hi -- This is our first test of the pull from fork process. https://github.com/wysiwhat/Aloha-Editor/edit/master/dev-workflow.md -- The pull requests should be to the "master" branch here rather than "dev". At least that is our current thinking.

**Comment by TomWoodward** [comment]
ok, if thats what you prefer i can cherry-pick the commits for all these PRs over to master and reissue.

**Comment by kathi-fletcher** [comment]
I don't think we need to redo-- Marvin has a plan. Just recording for the
future.

Ka

On Wed, Mar 6, 2013 at 10:09 AM, tmsp1 notifications@github.com wrote:

> ok, if thats what you prefer i can cherry-pick the commits for all these
> PRs over to master and reissue.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/wysiwhat/Aloha-Editor/pull/10#issuecomment-14507514
> .

## 

Katherine Fletcher, kathi.fletcher@gmail.com
kathi.fletcher@gmail.com
Twitter: kefletcher http://www.twitter.com/kefletcher Blog:
kefletcher.blogspot.com
kathi.fletcher@gmail.com

**Comment by kathi-fletcher** [comment]
This got closed because of the merge to dev, but really it is not yet done. Still working out kinks in the process. We don't know if the branch were off master and we had merged to dev whether it would close.

Tested and this worked by the way.

**Comment by TomWoodward** [comment]
yes all of these PRs were branched off of dev - I will work directly from master in the future if thats what you guys would like me to do.

in what way is this not done? is there something else that I need to do?

**Pull request merged**
